module.exports = {
  testEnvironment: "node",
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  collectCoverageFrom: [
    "src/**/*.js",
    "!src/app.js",
    "!**/node_modules/**",
    "!src/public/**/*.js",
  ],
  testMatch: ["**/tests/**/*.test.js"],
  testPathIgnorePatterns: ["src/public", "public", "node_modules"],
  setupFilesAfterEnv: ["<rootDir>/src/tests/setup.js"],
  verbose: true,
  forceExit: true,
  moduleNameMapper: {
    "^node:fs/promises$": "<rootDir>/__node_builtins__/fs-promises.js",
    "^node:fs$": "<rootDir>/__node_builtins__/fs.js",
    "^node:crypto$": "<rootDir>/__node_builtins__/crypto.js",
    "^node:events$": "<rootDir>/__node_builtins__/events.js",
    "^node:os$": "<rootDir>/__node_builtins__/os.js",
    "^node:path$": "<rootDir>/__node_builtins__/path.js",
    "^node:stream$": "<rootDir>/__node_builtins__/stream.js",
    "^node:string_decoder$": "<rootDir>/__node_builtins__/string_decoder.js",
    "^node:buffer$": "<rootDir>/__node_builtins__/buffer.js",
    "^node:util$": "<rootDir>/__node_builtins__/util.js",
    "^node:url$": "<rootDir>/__node_builtins__/url.js",
    "^node:http$": "<rootDir>/__node_builtins__/http.js",
    "^node:https$": "<rootDir>/__node_builtins__/https.js",
    "^node:net$": "<rootDir>/__node_builtins__/net.js",
    "^node:tls$": "<rootDir>/__node_builtins__/tls.js",
    "^node:zlib$": "<rootDir>/__node_builtins__/zlib.js",
    "^node:querystring$": "<rootDir>/__node_builtins__/querystring.js",
    "^jquery$": "jquery/dist/jquery.js",
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@tests/(.*)$": "<rootDir>/src/tests/$1",
    "^@root/(.*)$": "<rootDir>/$1",
  },
  transformIgnorePatterns: [
    "node_modules/(?!(jsdom|@exodus/bytes|@asamuzakjp|cssstyle|whatwg-encoding|whatwg-url|csscalc|csscolor|nwsapi|parse5|sax|symbol-tree|whatwg-mimetype|domexception|webidl-conversions|css-tree|mdn-data)/)",
  ],
  globals: {
    "ts-jest": {
      useESM: true,
    },
  },
};
