FROM node:22

# bashをインストール
RUN apt-get update && \
    apt-get install -y bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# GraphicsMagickとImageMagickをインストール
RUN apt-get update && \
    apt-get install -y graphicsmagick imagemagick && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/
# CMD /bin/bash -c "npm install && npm start"