# version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - ../db/:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    tty: true
      
  app:
    working_dir: /usr/app/
    build: .
    container_name: app
    volumes:
      - ../:/usr/app/
      - ./node_modules:/app/node_modules
    ports:
      - 80:80
    tty: true
    stdin_open: true

volumes:
  mysql_data: