FROM node:latest

WORKDIR /usr/app/
COPY start.sh /start.sh
RUN chmod 744 /start.sh

RUN apt-get update && \
    apt-get install -y bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y graphicsmagick imagemagick && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD [ "/start.sh" ]