CREATE DATABASE KASHIDASU CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE KASHIDASU;

CREATE TABLE ADMIN_USER(ID VARCHAR(10) PRIMARY KEY, USER_NAME VARCHAR(30), PASSWORD CHAR(30) CHARACTER SET utf8mb4);
CREATE TABLE BOOKS(ID VARCHAR(14) PRIMARY KEY, BOOK_NAME VARCHAR(50), WRITTER VARCHAR(30) CHARACTER SET utf8mb4);
CREATE TABLE LENDING_BOOK(BOOK_ID VARCHAR(14) PRIMARY KEY, USER_ID CHAR(10), LEND_DATE DATE, DEAD_LINE DATE);

INSERT INTO ADMIN_USER (ID, USER_NAME, PASSWORD) VALUES ("1234567891", "ゆっきー", "PASSWORD");