CREATE DATABASE KASHIDASU CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE KASHIDASU;

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE ADMIN_USER(
  ID VARCHAR(10) PRIMARY KEY,
  PASSWORD VARCHAR(255),
  LAST_NAME TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  FIRST_NAME TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE BOOKS(
  ID VARCHAR(14) PRIMARY KEY,
  BOOK_NAME VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  WRITTER VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE LENDING_BOOK(
  BOOK_ID VARCHAR(14) PRIMARY KEY,
  USER_ID CHAR(10),
  LEND_DAY DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;